### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by sylviashea1** [justinelliotmeyers/official_egypt_administrative_boundary_shapefile#1]
hello! is it possible for you to attach a screenshot of the email that grants permission to use the boundaries? it would be great to have a formal document that lays out terms of use.

**Comment by justinelliotmeyers** [comment]
https://github.com/dataslayer69/official_egypt_administrative_boundary_shapefile/blob/master/metadata.txt

let me know if this works - otherwise you can email them and ask too. Thanks!
